name: Run dbt core

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "protobuf<5.26.1" dbt-core==1.7.5 dbt-postgres  # Change dbt-postgres to your adapter (e.g., dbt-sqlserver, dbt-fabric)

      - name: Set up dbt profile
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.DBT_PROFILES_YML }}" > ~/.dbt/profiles.yml

      - name: dbt debug
        run: dbt debug

      - name: dbt deps
        run: dbt deps

      - name: dbt run
        run: dbt run

      - name: dbt test
        run: dbt test
