name: Run dbt with SQL Server

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  dbt-sqlserver:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dbt-core and SQL Server adapter
        run: |
          pip install --upgrade pip
          pip install dbt-core dbt-sqlserver

      - name: Create dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.DBT_SQLSERVER_PROFILE }}" > ~/.dbt/profiles.yml

      - name: dbt debug
        run: dbt debug

      - name: dbt deps
        run: dbt deps

      - name: dbt run
        run: dbt run

      - name: dbt test
        run: dbt test
