name: Run dbt with Microsoft Fabric

on:
  workflow_dispatch:  # manually triggered for now (can change)

jobs:
  dbt-fabric:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dbt-core and Fabric adapter
        run: |
          pip install --upgrade pip
          pip install dbt-core dbt-fabric

      - name: Set up profiles.yml
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.DBT_FABRIC_PROFILE }}" > ~/.dbt/profiles.yml

      - name: dbt debug
        run: dbt debug

      - name: dbt deps
        run: dbt deps

      - name: dbt run
        run: dbt run

      - name: dbt test
        run: dbt test
